// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT634vk6vZMaAc_zzt3zuwvhlJgjOs5LI',
    appId: '1:507046914533:web:996975add63813f9ff670c',
    messagingSenderId: '507046914533',
    projectId: 'ebookapp-9cdd5',
    authDomain: 'ebookapp-9cdd5.firebaseapp.com',
    storageBucket: 'ebookapp-9cdd5.firebasestorage.app',
    measurementId: 'G-11RC715F0B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh31sRHyTqhSUQfTi3DN9hGL9V7kMijuw',
    appId: '1:507046914533:android:55ab33ef055e389bff670c',
    messagingSenderId: '507046914533',
    projectId: 'ebookapp-9cdd5',
    storageBucket: 'ebookapp-9cdd5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyINV5ZaMRtXyjPE2Mfto0kHdfVWbOwWM',
    appId: '1:507046914533:ios:be0921b0fbdb3b8dff670c',
    messagingSenderId: '507046914533',
    projectId: 'ebookapp-9cdd5',
    storageBucket: 'ebookapp-9cdd5.firebasestorage.app',
    iosBundleId: 'com.ebook.ebookapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyINV5ZaMRtXyjPE2Mfto0kHdfVWbOwWM',
    appId: '1:507046914533:ios:be0921b0fbdb3b8dff670c',
    messagingSenderId: '507046914533',
    projectId: 'ebookapp-9cdd5',
    storageBucket: 'ebookapp-9cdd5.firebasestorage.app',
    iosBundleId: 'com.ebook.ebookapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAT634vk6vZMaAc_zzt3zuwvhlJgjOs5LI',
    appId: '1:507046914533:web:915698731fb9d0afff670c',
    messagingSenderId: '507046914533',
    projectId: 'ebookapp-9cdd5',
    authDomain: 'ebookapp-9cdd5.firebaseapp.com',
    storageBucket: 'ebookapp-9cdd5.firebasestorage.app',
    measurementId: 'G-JVSVQME9KC',
  );
}
